### ISSUE TITLE
properties$labels_dictionary is not used

### ISSUE THREAD

**Issue by RodGal-2020** [Xopre/RAPS#3]
As the title says, that object is not used, and therefore the resulting labels are the ones used inside P-Lingua 5.0, and not the real ones.

**Comment by RodGal-2020** [comment]
Okey, I've seen the "quickfix", but it needs some improvement

**Comment by Xopre** [comment]
It is used now, but there should be a translation function, just as there is for the objects. Working on it.

**Comment by Xopre** [comment]
With the new version this problem is solved. However, perhaps you would like to take a look at [the following issue](https://github.com/Xopre/RAPS/issues/4), as there are still problems to be solved.
