### ISSUE TITLE
Rules with where = "@exists" are not correctly read

### ISSUE THREAD

**Issue by RodGal-2020** [Xopre/RAPS#5]
Using the load_demo_dataset you can get some rules with `@exists` in the `where` section; however, when trying to use the `path2rap()` function with examples like [the following](https://github.com/Xopre/psystems-examples/tree/main/plingua5/RAPS/increasing_rules_communication), you can see that the `@exists` row disappears from the left-hand side of the rule.

**Comment by Xopre** [comment]
This issue will be treated for now on on [that other issue](https://github.com/Xopre/RAPS/issues/2).

Therefore, this issue is closed as it is duplicated.
