### ISSUE TITLE
The get_trinities function inside alg_det_menv doens't work

### ISSUE THREAD

**Issue by RodGal-2020** [Xopre/RAPS#7]
As I was saying, the `get_trinities()` function doesn't work, fact that we can see looking at the group of trinities it generates for the first step of the FAS rap, returning mostly `Inf`s in the `tau_i` column.

I hope this is fixed quickly.

Good luck! :D

**Comment by Xopre** [comment]
This was fixed with the last 3 commits.

The problem was due to a chain of bugs with the application functions. The computing of the trinities has been greately improved as a wanted side effect.

Regards,
Xopre
